In [13]:
import numpy as np
import pandas as pd

In [15]:
books = pd.read_csv('books.csv')
users = pd.read_csv('users.csv')
ratings = pd.read_csv('ratings.csv')

C:\Users\shett\AppData\Local\Temp\ipykernel_15332\3819754567.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('books.csv')


In [16]:


books.head()

ISBN                                         Book-Title  \
0  0195153448                                Classical Mythology   
1  0002005018                                       Clara Callan   
2  0060973129                               Decision in Normandy   
3  0374157065  Flu: The Story of the Great Influenza Pandemic...   
4  0393045218                             The Mummies of Urumchi   

            Book-Author Year-Of-Publication                   Publisher  \
0    Mark P. O. Morford                2002     Oxford University Press   
1  Richard Bruce Wright                2001       HarperFlamingo Canada   
2          Carlo D'Este                1991             HarperPerennial   
3      Gina Bari Kolata                1999        Farrar Straus Giroux   
4       E. J. W. Barber                1999  W. W. Norton &amp; Company   

                                         Image-URL-S  \
0  http://images.amazon.com/images/P/0195153448.0...   
1  http://images.amazon.com/images/P/0002005018.0...   
2  http://images.amazon.com/images/P/0060973129.0...   
3  http://images.amazon.com/images/P/0374157065.0...   
4  http://images.amazon.com/images/P/0393045218.0...   

                                         Image-URL-M  \
0  http://images.amazon.com/images/P/0195153448.0...   
1  http://images.amazon.com/images/P/0002005018.0...   
2  http://images.amazon.com/images/P/0060973129.0...   
3  http://images.amazon.com/images/P/0374157065.0...   
4  http://images.amazon.com/images/P/0393045218.0...   

                                         Image-URL-L  
0  http://images.amazon.com/images/P/0195153448.0...  
1  http://images.amazon.com/images/P/0002005018.0...  
2  http://images.amazon.com/images/P/0060973129.0...  
3  http://images.amazon.com/images/P/0374157065.0...  
4  http://images.amazon.com/images/P/0393045218.0...

In [17]:
users.head()

User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [19]:
ratings.head()

User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [23]:
print(books.shape)
print(users.shape)
print(ratings.shape)


(271360, 8)
(278858, 3)
(1149780, 3)


In [25]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [27]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [29]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [31]:
books.duplicated().sum()

0

In [33]:
ratings.duplicated().sum()


0

In [35]:
users.duplicated().sum()


0

## POPULARITY BASED RECOMMENDAION SYSTEM

In [38]:
ratings_with_name = ratings.merge(books,on='ISBN')

In [40]:
num_rating_df=ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
num_rating_df.rename(columns={'Book-Rating':'num-ratings'},inplace=True)
num_rating_df

Book-Title  num-ratings
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [42]:
avg_rating_df = ratings_with_name.groupby('Book-Title')['Book-Rating'].agg(lambda x: x.astype(float).mean()).reset_index()
avg_rating_df.rename(columns = {'Book-Rating' : 'avg_rating'}, inplace = True)
avg_rating_df



Book-Title  avg_rating
0        A Light in the Storm: The Civil War Diary of ...    2.250000
1                                   Always Have Popsicles    0.000000
2                    Apple Magic (The Collector's series)    0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...    8.000000
4        Beyond IBM: Leadership Marketing and Finance ...    0.000000
...                                                   ...         ...
241066                                      Ã?Â?lpiraten.    0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.    5.250000
241068                                Ã?Â?sterlich leben.    7.000000
241069                              Ã?Â?stlich der Berge.    2.666667
241070                                  Ã?Â?thique en toc    4.000000

[241071 rows x 2 columns]

In [43]:
popular_df= num_rating_df.merge(avg_rating_df,on='Book-Title')
popular_df

Book-Title  num-ratings  \
0        A Light in the Storm: The Civil War Diary of ...            4   
1                                   Always Have Popsicles            1   
2                    Apple Magic (The Collector's series)            1   
3        Ask Lily (Young Women of Faith: Lily Series, ...            1   
4        Beyond IBM: Leadership Marketing and Finance ...            1   
...                                                   ...          ...   
241066                                      Ã?Â?lpiraten.            2   
241067                     Ã?Â?rger mit Produkt X. Roman.            4   
241068                                Ã?Â?sterlich leben.            1   
241069                              Ã?Â?stlich der Berge.            3   
241070                                  Ã?Â?thique en toc            2   

        avg_rating  
0         2.250000  
1         0.000000  
2         0.000000  
3         8.000000  
4         0.000000  
...            ...  
241066    0.000000  
241067    5.250000  
241068    7.000000  
241069    2.666667  
241070    4.000000  

[241071 rows x 3 columns]

In [44]:
popular_df = popular_df[popular_df['num-ratings']>=250].sort_values('avg_rating',ascending=False).head(50)



In [45]:
popular_df = popular_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title', 'Book-Author','Image-URL-M','num-ratings','avg_rating']]

In [46]:
popular_df

Book-Title  \
0    Harry Potter and the Prisoner of Azkaban (Book 3)   
3         Harry Potter and the Goblet of Fire (Book 4)   
5       Harry Potter and the Sorcerer's Stone (Book 1)   
9    Harry Potter and the Order of the Phoenix (Boo...   
13    Harry Potter and the Chamber of Secrets (Book 2)   
16   The Hobbit : The Enchanting Prelude to The Lor...   
17   The Fellowship of the Ring (The Lord of the Ri...   
26   Harry Potter and the Sorcerer's Stone (Harry P...   
28      The Two Towers (The Lord of the Rings, Part 2)   
39                               To Kill a Mockingbird   
47                                   The Da Vinci Code   
53                  The Five People You Meet in Heaven   
55                              The Catcher in the Rye   
62                           The Lovely Bones: A Novel   
63                                                1984   
72                            Prodigal Summer: A Novel   
73                                          Neverwhere   
78                             The Secret Life of Bees   
84   Stupid White Men ...and Other Sorry Excuses fo...   
85   Tuesdays with Morrie: An Old Man, a Young Man,...   
88                 The Red Tent (Bestselling Backlist)   
89                The Hitchhiker's Guide to the Galaxy   
98    Nickel and Dimed: On (Not) Getting By in America   
100                                      Into the Wild   
103                                     Fahrenheit 451   
116                          Girl with a Pearl Earring   
117                                          Outlander   
123  Where the Heart Is (Oprah's Book Club (Paperba...   
124                     Seabiscuit: An American Legend   
126                                         Life of Pi   
130                                     The Bean Trees   
133  A Child Called \It\": One Child's Courage to S...   
135                                     ANGELA'S ASHES   
137                                        Good in Bed   
139  Fast Food Nation: The Dark Side of the All-Ame...   
140                                      American Gods   
141                                 Skipping Christmas   
147  Left Behind: A Novel of the Earth's Last Days ...   
149    The Golden Compass (His Dark Materials, Book 1)   
157                                   The Color Purple   
163                               Silence of the Lambs   
166                                        About a Boy   
173                  Seven Up (A Stephanie Plum Novel)   
175  The Alchemist: A Fable About Following Your Dream   
177  Hard Eight : A Stephanie Plum Novel (A Stephan...   
182                       Suzanne's Diary for Nicholas   
186                                  Lord of the Flies   
192                            A Prayer for Owen Meany   
194   The Vampire Lestat (Vampire Chronicles, Book II)   
195       White Oleander : A Novel (Oprah's Book Club)   

                Book-Author  \
0             J. K. Rowling   
3             J. K. Rowling   
5             J. K. Rowling   
9             J. K. Rowling   
13            J. K. Rowling   
16           J.R.R. TOLKIEN   
17           J.R.R. TOLKIEN   
26            J. K. Rowling   
28           J.R.R. TOLKIEN   
39               Harper Lee   
47                Dan Brown   
53              Mitch Albom   
55            J.D. Salinger   
62             Alice Sebold   
63            George Orwell   
72       Barbara Kingsolver   
73              Neil Gaiman   
78            Sue Monk Kidd   
84            Michael Moore   
85              MITCH ALBOM   
88            Anita Diamant   
89            Douglas Adams   
98       Barbara Ehrenreich   
100            Jon Krakauer   
103            Ray Bradbury   
116         Tracy Chevalier   
117          DIANA GABALDON   
123            Billie Letts   
124       LAURA HILLENBRAND   
126             Yann Martel   
130      Barbara Kingsolver   
133             Dave Pelzer   
135           Frank McCourt   
137         Jennifer Weiner   


## colaborative based

In [53]:
x=ratings_with_name.groupby('User-ID').count()['Book-Rating']>200
good_users = x[x].index



In [55]:
filtered_rating=ratings_with_name[ratings_with_name['User-ID'].isin(good_users)]

In [57]:
y=filtered_rating.groupby('Book-Title').count()['Book-Rating']>=50
famous_books=y[y].index

In [59]:
final_ratings=filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]

In [61]:
pt=final_ratings.pivot_table(index='Book-Title',columns='User-ID',values='Book-Rating')

In [63]:
pt.fillna(0,inplace=True)


In [65]:
pt

User-ID                                             254     2276    2766    \
Book-Title                                                                   
1984                                                   9.0     0.0     0.0   
1st to Die: A Novel                                    0.0     0.0     0.0   
2nd Chance                                             0.0    10.0     0.0   
4 Blondes                                              0.0     0.0     0.0   
A Bend in the Road                                     0.0     0.0     7.0   
...                                                    ...     ...     ...   
Year of Wonders                                        0.0     0.0     0.0   
You Belong To Me                                       0.0     0.0     0.0   
Zen and the Art of Motorcycle Maintenance: An I...     0.0     0.0     0.0   
Zoya                                                   0.0     0.0     0.0   
\O\" Is for Outlaw"                                    0.0     0.0     0.0   

User-ID                                             2977    3363    4017    \
Book-Title                                                                   
1984                                                   0.0     0.0     0.0   
1st to Die: A Novel                                    0.0     0.0     0.0   
2nd Chance                                             0.0     0.0     0.0   
4 Blondes                                              0.0     0.0     0.0   
A Bend in the Road                                     0.0     0.0     0.0   
...                                                    ...     ...     ...   
Year of Wonders                                        7.0     0.0     0.0   
You Belong To Me                                       0.0     0.0     0.0   
Zen and the Art of Motorcycle Maintenance: An I...     0.0     0.0     0.0   
Zoya                                                   0.0     0.0     0.0   
\O\" Is for Outlaw"                                    0.0     0.0     0.0   

User-ID                                             4385    6251    6323    \
Book-Title                                                                   
1984                                                   0.0     0.0     0.0   
1st to Die: A Novel                                    0.0     0.0     0.0   
2nd Chance                                             0.0     0.0     0.0   
4 Blondes                                              0.0     0.0     0.0   
A Bend in the Road                                     0.0     0.0     0.0   
...                                                    ...     ...     ...   
Year of Wonders                                        0.0     0.0     0.0   
You Belong To Me                                       0.0     0.0     0.0   
Zen and the Art of Motorcycle Maintenance: An I...     0.0     0.0     0.0   
Zoya                                                   0.0     0.0     0.0   
\O\" Is for Outlaw"                                    0.0     0.0     0.0   

User-ID                                             6543    ...  271705  \
Book-Title                                                  ...           
1984                                                   0.0  ...    10.0   
1st to Die: A Novel                                    9.0  ...     0.0   
2nd Chance                                             0.0  ...     0.0   
4 Blondes                                              0.0  ...     0.0   
A Bend in the Road                                     0.0  ...     0.0   
...                                                    ...  ...     ...   
Year of Wonders                                        0.0  ...     0.0   
You Belong To Me                                       0.0  ...     0.0   
Zen and the Art of Motorcycle Maintenance: An I...     0.0  ...     0.0   
Zoya                                                   0.0  ...     0.0   
\O\" Is for Outlaw"                                    

In [67]:
from sklearn.metrics.pairwise import cosine_similarity

In [69]:
similarity_score=cosine_similarity(pt)


In [71]:
similarity_score.shape

(706, 706)

In [73]:
def recommend(book_name):
    # index fetch
    index = np.where(pt.index==book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_score[index])),key=lambda x:x[1],reverse=True)[1:5]
    
    data = []
    for i in similar_items:
        item = []
        temp_df = books[books['Book-Title'] == pt.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-M'].values))
        
        data.append(item)
    
    return data





In [75]:
recommend('1984')

[['Animal Farm',
  'George Orwell',
  'http://images.amazon.com/images/P/0451526341.01.MZZZZZZZ.jpg'],
 ["The Handmaid's Tale",
  'Margaret Atwood',
  'http://images.amazon.com/images/P/0449212602.01.MZZZZZZZ.jpg'],
 ['Brave New World',
  'Aldous Huxley',
  'http://images.amazon.com/images/P/0060809833.01.MZZZZZZZ.jpg'],
 ['The Vampire Lestat (Vampire Chronicles, Book II)',
  'ANNE RICE',
  'http://images.amazon.com/images/P/0345313860.01.MZZZZZZZ.jpg']]

In [77]:
import pickle
pickle.dump(popular_df,open('popular.pkl','wb'))

In [79]:
pickle.dump(pt,open('pt.pkl','wb'))
pickle.dump(books,open('books.pkl','wb'))
pickle.dump(similarity_score,open('similarity_score.pkl','wb'))

In [113]:
# import pandas as pd
# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.metrics.pairwise import linear_kernel
# import pickle

# # Load your books dataset
# books = pd.read_csv('Books.csv')

# # Sample 10,000 rows for testing
# books_sample = books.sample(n=10000, random_state=1)

# # Assuming your dataset has a 'Book-Title' column and a 'Description' column
# books_sample['Description'] = books_sample['Book-Title']  # Or combine with other columns if needed

# # Initialize TF-IDF Vectorizer with limited features
# tfidf = TfidfVectorizer(stop_words='english', max_features=10000)
# tfidf_matrix = tfidf.fit_transform(books_sample['Description'])

# # Compute cosine similarity matrix
# cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

# # Create a reverse mapping of indices and book titles
# indices = pd.Series(books_sample.index, index=books_sample['Book-Title']).drop_duplicates()

# def get_recommendations(title, cosine_sim=cosine_sim):
#     idx = indices.get(title)
#     sim_scores = list(enumerate(cosine_sim[idx]))
#     sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)[1:6]
#     book_indices = [i[0] for i in sim_scores]
#     return books_sample.iloc[book_indices]

# # Save the cosine similarity matrix and indices for use in Flask app
# pickle.dump(cosine_sim, open('content_based_similarity.pkl', 'wb'))
# pickle.dump(indices, open('indices.pkl', 'wb'))

# # Example usage
# recommendations = get_recommendations('1984')  # Replace with an actual book title
# print(recommendations[['Book-Title', 'Book-Author']])  # Adjust column names if necessary


C:\Users\shett\AppData\Local\Temp\ipykernel_15332\950012987.py:7: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('Books.csv')


                                          Book-Title        Book-Author
80771                             The Night Lives on        Walter Lord
201669  Heimskringla or the Lives of the Norse Kings   Snorri Sturluson
83503                            Lives of the saints         Nino Ricci
189191                The Lives of Christopher Chant  Diana Wynne Jones
264772                               Fortunate Lives   Robb Foreman Dew


In [117]:
print(cosine_sim)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [5]:
import pickle
import pandas as pd
df1=pd.read_csv('Ratings.csv')
df2=pd.read_pickle('similarity_score.pkl')

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [23]:
import pandas as pd
import pickle

# Load the CSV file
csv_file = 'Ratings.csv'  # Replace with your CSV file path
df = pd.read_csv(csv_file)

# Specify the index of the row you want to add (e.g., the first row)
row_to_add = df.iloc[0]  # Replace 0 with the index of the desired row

# Load the existing pickle file
with open('books.pkl', 'rb') as pkl_file:
    existing_data = pickle.load(pkl_file)

# Create a new list or DataFrame that includes both the existing data and the new row
# If existing_data is a list, append the new row as a dictionary
new_data = existing_data + [row_to_add.to_dict()]  # Convert the Series to a dictionary

# If existing_data is a DataFrame, you can concatenate instead:
# new_data = pd.concat([existing_data, row_to_add.to_frame().T], ignore_index=True)

# Save the combined data to a new pickle file
with open('Book.pkl', 'wb') as new_pkl_file:
    pickle.dump(new_data, new_pkl_file)

print("Row added to the new pickle file successfully!")


ValueError: Unable to coerce to Series, length must be 8: given 1

In [17]:
import pandas as pd
import pickle

# Load the CSV file
csv_file = 'Ratings.csv'  # Replace with your CSV file path
df = pd.read_csv(csv_file)

# Specify the index of the row you want to add (e.g., the first row)
row_to_add = df.iloc[0]  # Replace 0 with the index of the desired row

# Load the existing pickle file
with open('similarity_score.pkl', 'rb') as pkl_file:
    existing_data = pickle.load(pkl_file)

# Print the type and structure of existing_data for debugging
print("Type of existing_data:", type(existing_data))
print("Contents of existing_data:", existing_data)

# Check the type of existing_data and combine accordingly
if isinstance(existing_data, list):
    # If existing_data is a list, append the new row as a dictionary
    new_data = existing_data + [row_to_add.to_dict()]
elif isinstance(existing_data, pd.DataFrame):
    # If existing_data is a DataFrame, concatenate the new row
    new_data = pd.concat([existing_data, row_to_add.to_frame().T], ignore_index=True)
else:
    raise ValueError("Unexpected type for existing_data: {}".format(type(existing_data)))

# Save the combined data to a new pickle file
with open('new_cosine_similarity.pkl', 'wb') as new_pkl_file:
    pickle.dump(new_data, new_pkl_file)

print("Row added to the new pickle file successfully!")


Type of existing_data: <class 'numpy.ndarray'>
Contents of existing_data: [[1.         0.10255025 0.01220856 ... 0.12110367 0.07347567 0.04316046]
 [0.10255025 1.         0.2364573  ... 0.07446129 0.16773875 0.14263397]
 [0.01220856 0.2364573  1.         ... 0.04558758 0.04938579 0.10796119]
 ...
 [0.12110367 0.07446129 0.04558758 ... 1.         0.07085128 0.0196177 ]
 [0.07347567 0.16773875 0.04938579 ... 0.07085128 1.         0.10602962]
 [0.04316046 0.14263397 0.10796119 ... 0.0196177  0.10602962 1.        ]]


ValueError: Unexpected type for existing_data: <class 'numpy.ndarray'>

In [21]:
import pickle
import pandas
df=pd.read_pickle('books.pkl')
df.head()

ISBN                                         Book-Title  \
0  0195153448                                Classical Mythology   
1  0002005018                                       Clara Callan   
2  0060973129                               Decision in Normandy   
3  0374157065  Flu: The Story of the Great Influenza Pandemic...   
4  0393045218                             The Mummies of Urumchi   

            Book-Author Year-Of-Publication                   Publisher  \
0    Mark P. O. Morford                2002     Oxford University Press   
1  Richard Bruce Wright                2001       HarperFlamingo Canada   
2          Carlo D'Este                1991             HarperPerennial   
3      Gina Bari Kolata                1999        Farrar Straus Giroux   
4       E. J. W. Barber                1999  W. W. Norton &amp; Company   

                                         Image-URL-S  \
0  http://images.amazon.com/images/P/0195153448.0...   
1  http://images.amazon.com/images/P/0002005018.0...   
2  http://images.amazon.com/images/P/0060973129.0...   
3  http://images.amazon.com/images/P/0374157065.0...   
4  http://images.amazon.com/images/P/0393045218.0...   

                                         Image-URL-M  \
0  http://images.amazon.com/images/P/0195153448.0...   
1  http://images.amazon.com/images/P/0002005018.0...   
2  http://images.amazon.com/images/P/0060973129.0...   
3  http://images.amazon.com/images/P/0374157065.0...   
4  http://images.amazon.com/images/P/0393045218.0...   

                                         Image-URL-L  
0  http://images.amazon.com/images/P/0195153448.0...  
1  http://images.amazon.com/images/P/0002005018.0...  
2  http://images.amazon.com/images/P/0060973129.0...  
3  http://images.amazon.com/images/P/0374157065.0...  
4  http://images.amazon.com/images/P/0393045218.0...

In [27]:
import pandas as pd
import pickle

# Load the CSV file
csv_file = 'Ratings.csv'  # Replace with your CSV file path
df = pd.read_csv(csv_file)

# Specify the index of the row you want to add (e.g., the first row)
row_to_add = df.iloc[0]  # Replace 0 with the index of the desired row

# Load the existing pickle file
with open('books.pkl', 'rb') as pkl_file:
    existing_data = pickle.load(pkl_file)

# Print the type and structure of existing_data for debugging
print("Type of existing_data:", type(existing_data))
print("Contents of existing_data:", existing_data)

# Check the structure of existing_data
if isinstance(existing_data, pd.DataFrame):
    print("Shape of existing_data:", existing_data.shape)
    print("Columns of existing_data:", existing_data.columns.tolist())
elif isinstance(existing_data, list):
    print("Length of existing_data list:", len(existing_data))
else:
    raise ValueError("Unexpected type for existing_data: {}".format(type(existing_data)))

# Create a new row DataFrame for concatenation
new_row_df = row_to_add.to_frame().T  # Convert Series to DataFrame

# Check if the new row has the same columns as the existing data
if isinstance(existing_data, pd.DataFrame):
    if not new_row_df.columns.equals(existing_data.columns):
        raise ValueError("Column mismatch: Existing data columns do not match new row columns.")

    # Concatenate the DataFrames
    new_data = pd.concat([existing_data, new_row_df], ignore_index=True)
elif isinstance(existing_data, list):
    # If existing_data is a list, append the new row as a dictionary
    new_data = existing_data + [row_to_add.to_dict()]

# Save the combined data to a new pickle file
with open('Book.pkl', 'wb') as new_pkl_file:
    pickle.dump(new_data, new_pkl_file)

print("Row added to the new pickle file successfully!")


Type of existing_data: <class 'pandas.core.frame.DataFrame'>
Contents of existing_data:               ISBN                                         Book-Title  \
0       0195153448                                Classical Mythology   
1       0002005018                                       Clara Callan   
2       0060973129                               Decision in Normandy   
3       0374157065  Flu: The Story of the Great Influenza Pandemic...   
4       0393045218                             The Mummies of Urumchi   
...            ...                                                ...   
271355  0440400988                         There's a Bat in Bunk Five   
271356  0525447644                            From One to One Hundred   
271357  006008667X  Lily Dale : The True Story of the Town that Ta...   
271358  0192126040                        Republic (World's Classics)   
271359  0767409752  A Guided Tour of Rene Descartes' Meditations o...   

                 Book-Author Year-O

ValueError: Column mismatch: Existing data columns do not match new row columns.